---
# Ansible extra variables generated by Terraform

domain_name: "${domain_name}"
letsencrypt_email: "${letsencrypt_email}"
jwt_secret: "${jwt_secret}"
github_repo_url: "${github_repo_url}"
app_directory: "${app_directory}"
docker_compose_version: "2.23.0"

